name: Add Members
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  add:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install dependencies
        run: |
          npm install cross-fetch
      - name: Config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout "${GITHUB_REF:11}"
          git pull
      - name: Get members
        run: |
          node ci/update.js
      - name: Add, Commit and Push
        run: |
          git add data.json
          git commit -m "Update members list"
          git push
